#! /usr/bin/bash
echo "Installing the command line utility....."
echo "Copying files to user bin....."
cp -rf ../coding_template ~/bin
echo "Creating user alias"
echo 'alias template="~/bin/coding_template/template"' >> ~/.bashrc
echo "USE template -h to get usage"
bash
